### PR TITLE
General nn

### PR DESCRIPTION
**Pull request by sallamander**
@jliemansifry @Ultramann Take a look when you get a chance please! I added some stuff on activation functions, and reformatted @jliemansifry recent changes. 

:facepunch:

### CODE REVIEW

**Comment by sallamander** [comment]
@Ultramann @jliemansifry You guys good with me merging this in?

**Comment by Ultramann** [comment]
@sallamander You're doing way more work than me on everything. I'll try to look at this if you want me to before merge. Otherwise, merge away! #yolobrolo

**Comment by jliemansifry** [comment]
@sallamander Looks good to me. Kind of interesting that the research went away from the perceptron and is now has a branch headed back in that direction (non-continuous outputs) with XNOR-Net (http://arxiv.org/pdf/1603.05279v1.pdf)

**Comment by sallamander** [comment]
@jliemansifry Yeah, interesting. I've put that article on my list! Hope you make it to the motherland safely!! :car: :blue_car:

**Pull request merged**
